name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Test and Generate Coverage Report
        run: mvn jacoco:prepare-agent test install jacoco:report
      
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: dockside
          postgresql user: dockside
          postgresql password: dockside_1234